### ISSUE TITLE
#with_lang(block_name) not working

### ISSUE THREAD

**Issue by Assassin4b** [alcatrazEscapee/mcresources#2]
#with_lang() doesn't seem to work, no lang file gets created. Maybe im doing something wrong, please add further explanation about it then.

**Comment by alcatrazEscapee** [comment]
Lang files and tags accumulate all entries in a buffer in the `ResourceManager`. (So, multiple calls to `with_lang` or `with_tag` or any other methods don't directly write files as typically there will be many lines of lang, or different blocks that add themselves to tags). In order to actually write the files you need to call `ResourceManager#flush`:

```python
rm = ResourceManager()
rm.lang('key', 'value')
rm.flush()  # lang file is now written
```

This is referenced in the documentation although it could probably be more ovbious.

> In addition, this delegated behavior also applies to tags. Tags no longer create single files every time the relevant tag method is called. Instead, they accumulate tag entries in a buffer, allowing multiple tag calls to append entries to a single tag.
> 
> In order to finalize tag (and lang / translation) entries, a call to ResourceManager#flush is necessary, which will clear the current buffer for tags and translation entries and write all relevant files.
